################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/json/doc/examples/README.cpp \
../src/json/doc/examples/accept__string.cpp \
../src/json/doc/examples/array.cpp \
../src/json/doc/examples/at__object_t_key_type.cpp \
../src/json/doc/examples/at__object_t_key_type_const.cpp \
../src/json/doc/examples/at__size_type.cpp \
../src/json/doc/examples/at__size_type_const.cpp \
../src/json/doc/examples/at_json_pointer.cpp \
../src/json/doc/examples/at_json_pointer_const.cpp \
../src/json/doc/examples/back.cpp \
../src/json/doc/examples/basic_json__CompatibleType.cpp \
../src/json/doc/examples/basic_json__InputIt_InputIt.cpp \
../src/json/doc/examples/basic_json__basic_json.cpp \
../src/json/doc/examples/basic_json__copyassignment.cpp \
../src/json/doc/examples/basic_json__list_init_t.cpp \
../src/json/doc/examples/basic_json__moveconstructor.cpp \
../src/json/doc/examples/basic_json__nullptr_t.cpp \
../src/json/doc/examples/basic_json__size_type_basic_json.cpp \
../src/json/doc/examples/basic_json__value.cpp \
../src/json/doc/examples/basic_json__value_ptr.cpp \
../src/json/doc/examples/basic_json__value_t.cpp \
../src/json/doc/examples/begin.cpp \
../src/json/doc/examples/cbegin.cpp \
../src/json/doc/examples/cend.cpp \
../src/json/doc/examples/clear.cpp \
../src/json/doc/examples/contains.cpp \
../src/json/doc/examples/contains_json_pointer.cpp \
../src/json/doc/examples/count.cpp \
../src/json/doc/examples/crbegin.cpp \
../src/json/doc/examples/crend.cpp \
../src/json/doc/examples/diff.cpp \
../src/json/doc/examples/dump.cpp \
../src/json/doc/examples/emplace.cpp \
../src/json/doc/examples/emplace_back.cpp \
../src/json/doc/examples/empty.cpp \
../src/json/doc/examples/end.cpp \
../src/json/doc/examples/erase__IteratorType.cpp \
../src/json/doc/examples/erase__IteratorType_IteratorType.cpp \
../src/json/doc/examples/erase__key_type.cpp \
../src/json/doc/examples/erase__size_type.cpp \
../src/json/doc/examples/exception.cpp \
../src/json/doc/examples/find__key_type.cpp \
../src/json/doc/examples/flatten.cpp \
../src/json/doc/examples/from_bson.cpp \
../src/json/doc/examples/from_cbor.cpp \
../src/json/doc/examples/from_msgpack.cpp \
../src/json/doc/examples/from_ubjson.cpp \
../src/json/doc/examples/front.cpp \
../src/json/doc/examples/get__PointerType.cpp \
../src/json/doc/examples/get__ValueType_const.cpp \
../src/json/doc/examples/get_ptr.cpp \
../src/json/doc/examples/get_ref.cpp \
../src/json/doc/examples/get_to.cpp \
../src/json/doc/examples/insert.cpp \
../src/json/doc/examples/insert__count.cpp \
../src/json/doc/examples/insert__ilist.cpp \
../src/json/doc/examples/insert__range.cpp \
../src/json/doc/examples/insert__range_object.cpp \
../src/json/doc/examples/invalid_iterator.cpp \
../src/json/doc/examples/is_array.cpp \
../src/json/doc/examples/is_binary.cpp \
../src/json/doc/examples/is_boolean.cpp \
../src/json/doc/examples/is_discarded.cpp \
../src/json/doc/examples/is_null.cpp \
../src/json/doc/examples/is_number.cpp \
../src/json/doc/examples/is_number_float.cpp \
../src/json/doc/examples/is_number_integer.cpp \
../src/json/doc/examples/is_number_unsigned.cpp \
../src/json/doc/examples/is_object.cpp \
../src/json/doc/examples/is_primitive.cpp \
../src/json/doc/examples/is_string.cpp \
../src/json/doc/examples/is_structured.cpp \
../src/json/doc/examples/items.cpp \
../src/json/doc/examples/iterator_wrapper.cpp \
../src/json/doc/examples/json_pointer.cpp \
../src/json/doc/examples/json_pointer__back.cpp \
../src/json/doc/examples/json_pointer__empty.cpp \
../src/json/doc/examples/json_pointer__operator_add.cpp \
../src/json/doc/examples/json_pointer__operator_add_binary.cpp \
../src/json/doc/examples/json_pointer__parent_pointer.cpp \
../src/json/doc/examples/json_pointer__pop_back.cpp \
../src/json/doc/examples/json_pointer__push_back.cpp \
../src/json/doc/examples/json_pointer__to_string.cpp \
../src/json/doc/examples/max_size.cpp \
../src/json/doc/examples/merge_patch.cpp \
../src/json/doc/examples/meta.cpp \
../src/json/doc/examples/object.cpp \
../src/json/doc/examples/operator__ValueType.cpp \
../src/json/doc/examples/operator__equal.cpp \
../src/json/doc/examples/operator__equal__nullptr_t.cpp \
../src/json/doc/examples/operator__greater.cpp \
../src/json/doc/examples/operator__greaterequal.cpp \
../src/json/doc/examples/operator__less.cpp \
../src/json/doc/examples/operator__lessequal.cpp \
../src/json/doc/examples/operator__notequal.cpp \
../src/json/doc/examples/operator__notequal__nullptr_t.cpp \
../src/json/doc/examples/operator__value_t.cpp \
../src/json/doc/examples/operator_deserialize.cpp \
../src/json/doc/examples/operator_serialize.cpp \
../src/json/doc/examples/operatorarray__key_type.cpp \
../src/json/doc/examples/operatorarray__key_type_const.cpp \
../src/json/doc/examples/operatorarray__size_type.cpp \
../src/json/doc/examples/operatorarray__size_type_const.cpp \
../src/json/doc/examples/operatorjson_pointer.cpp \
../src/json/doc/examples/operatorjson_pointer_const.cpp \
../src/json/doc/examples/other_error.cpp \
../src/json/doc/examples/out_of_range.cpp \
../src/json/doc/examples/parse__array__parser_callback_t.cpp \
../src/json/doc/examples/parse__contiguouscontainer__parser_callback_t.cpp \
../src/json/doc/examples/parse__istream__parser_callback_t.cpp \
../src/json/doc/examples/parse__iteratortype__parser_callback_t.cpp \
../src/json/doc/examples/parse__string__parser_callback_t.cpp \
../src/json/doc/examples/parse_error.cpp \
../src/json/doc/examples/patch.cpp \
../src/json/doc/examples/push_back.cpp \
../src/json/doc/examples/push_back__initializer_list.cpp \
../src/json/doc/examples/push_back__object_t__value.cpp \
../src/json/doc/examples/rbegin.cpp \
../src/json/doc/examples/rend.cpp \
../src/json/doc/examples/sax_parse.cpp \
../src/json/doc/examples/size.cpp \
../src/json/doc/examples/swap__array_t.cpp \
../src/json/doc/examples/swap__binary_t.cpp \
../src/json/doc/examples/swap__object_t.cpp \
../src/json/doc/examples/swap__reference.cpp \
../src/json/doc/examples/swap__string_t.cpp \
../src/json/doc/examples/to_bson.cpp \
../src/json/doc/examples/to_cbor.cpp \
../src/json/doc/examples/to_msgpack.cpp \
../src/json/doc/examples/to_ubjson.cpp \
../src/json/doc/examples/type.cpp \
../src/json/doc/examples/type_error.cpp \
../src/json/doc/examples/type_name.cpp \
../src/json/doc/examples/unflatten.cpp \
../src/json/doc/examples/update.cpp \
../src/json/doc/examples/update__range.cpp 

OBJS += \
./src/json/doc/examples/README.o \
./src/json/doc/examples/accept__string.o \
./src/json/doc/examples/array.o \
./src/json/doc/examples/at__object_t_key_type.o \
./src/json/doc/examples/at__object_t_key_type_const.o \
./src/json/doc/examples/at__size_type.o \
./src/json/doc/examples/at__size_type_const.o \
./src/json/doc/examples/at_json_pointer.o \
./src/json/doc/examples/at_json_pointer_const.o \
./src/json/doc/examples/back.o \
./src/json/doc/examples/basic_json__CompatibleType.o \
./src/json/doc/examples/basic_json__InputIt_InputIt.o \
./src/json/doc/examples/basic_json__basic_json.o \
./src/json/doc/examples/basic_json__copyassignment.o \
./src/json/doc/examples/basic_json__list_init_t.o \
./src/json/doc/examples/basic_json__moveconstructor.o \
./src/json/doc/examples/basic_json__nullptr_t.o \
./src/json/doc/examples/basic_json__size_type_basic_json.o \
./src/json/doc/examples/basic_json__value.o \
./src/json/doc/examples/basic_json__value_ptr.o \
./src/json/doc/examples/basic_json__value_t.o \
./src/json/doc/examples/begin.o \
./src/json/doc/examples/cbegin.o \
./src/json/doc/examples/cend.o \
./src/json/doc/examples/clear.o \
./src/json/doc/examples/contains.o \
./src/json/doc/examples/contains_json_pointer.o \
./src/json/doc/examples/count.o \
./src/json/doc/examples/crbegin.o \
./src/json/doc/examples/crend.o \
./src/json/doc/examples/diff.o \
./src/json/doc/examples/dump.o \
./src/json/doc/examples/emplace.o \
./src/json/doc/examples/emplace_back.o \
./src/json/doc/examples/empty.o \
./src/json/doc/examples/end.o \
./src/json/doc/examples/erase__IteratorType.o \
./src/json/doc/examples/erase__IteratorType_IteratorType.o \
./src/json/doc/examples/erase__key_type.o \
./src/json/doc/examples/erase__size_type.o \
./src/json/doc/examples/exception.o \
./src/json/doc/examples/find__key_type.o \
./src/json/doc/examples/flatten.o \
./src/json/doc/examples/from_bson.o \
./src/json/doc/examples/from_cbor.o \
./src/json/doc/examples/from_msgpack.o \
./src/json/doc/examples/from_ubjson.o \
./src/json/doc/examples/front.o \
./src/json/doc/examples/get__PointerType.o \
./src/json/doc/examples/get__ValueType_const.o \
./src/json/doc/examples/get_ptr.o \
./src/json/doc/examples/get_ref.o \
./src/json/doc/examples/get_to.o \
./src/json/doc/examples/insert.o \
./src/json/doc/examples/insert__count.o \
./src/json/doc/examples/insert__ilist.o \
./src/json/doc/examples/insert__range.o \
./src/json/doc/examples/insert__range_object.o \
./src/json/doc/examples/invalid_iterator.o \
./src/json/doc/examples/is_array.o \
./src/json/doc/examples/is_binary.o \
./src/json/doc/examples/is_boolean.o \
./src/json/doc/examples/is_discarded.o \
./src/json/doc/examples/is_null.o \
./src/json/doc/examples/is_number.o \
./src/json/doc/examples/is_number_float.o \
./src/json/doc/examples/is_number_integer.o \
./src/json/doc/examples/is_number_unsigned.o \
./src/json/doc/examples/is_object.o \
./src/json/doc/examples/is_primitive.o \
./src/json/doc/examples/is_string.o \
./src/json/doc/examples/is_structured.o \
./src/json/doc/examples/items.o \
./src/json/doc/examples/iterator_wrapper.o \
./src/json/doc/examples/json_pointer.o \
./src/json/doc/examples/json_pointer__back.o \
./src/json/doc/examples/json_pointer__empty.o \
./src/json/doc/examples/json_pointer__operator_add.o \
./src/json/doc/examples/json_pointer__operator_add_binary.o \
./src/json/doc/examples/json_pointer__parent_pointer.o \
./src/json/doc/examples/json_pointer__pop_back.o \
./src/json/doc/examples/json_pointer__push_back.o \
./src/json/doc/examples/json_pointer__to_string.o \
./src/json/doc/examples/max_size.o \
./src/json/doc/examples/merge_patch.o \
./src/json/doc/examples/meta.o \
./src/json/doc/examples/object.o \
./src/json/doc/examples/operator__ValueType.o \
./src/json/doc/examples/operator__equal.o \
./src/json/doc/examples/operator__equal__nullptr_t.o \
./src/json/doc/examples/operator__greater.o \
./src/json/doc/examples/operator__greaterequal.o \
./src/json/doc/examples/operator__less.o \
./src/json/doc/examples/operator__lessequal.o \
./src/json/doc/examples/operator__notequal.o \
./src/json/doc/examples/operator__notequal__nullptr_t.o \
./src/json/doc/examples/operator__value_t.o \
./src/json/doc/examples/operator_deserialize.o \
./src/json/doc/examples/operator_serialize.o \
./src/json/doc/examples/operatorarray__key_type.o \
./src/json/doc/examples/operatorarray__key_type_const.o \
./src/json/doc/examples/operatorarray__size_type.o \
./src/json/doc/examples/operatorarray__size_type_const.o \
./src/json/doc/examples/operatorjson_pointer.o \
./src/json/doc/examples/operatorjson_pointer_const.o \
./src/json/doc/examples/other_error.o \
./src/json/doc/examples/out_of_range.o \
./src/json/doc/examples/parse__array__parser_callback_t.o \
./src/json/doc/examples/parse__contiguouscontainer__parser_callback_t.o \
./src/json/doc/examples/parse__istream__parser_callback_t.o \
./src/json/doc/examples/parse__iteratortype__parser_callback_t.o \
./src/json/doc/examples/parse__string__parser_callback_t.o \
./src/json/doc/examples/parse_error.o \
./src/json/doc/examples/patch.o \
./src/json/doc/examples/push_back.o \
./src/json/doc/examples/push_back__initializer_list.o \
./src/json/doc/examples/push_back__object_t__value.o \
./src/json/doc/examples/rbegin.o \
./src/json/doc/examples/rend.o \
./src/json/doc/examples/sax_parse.o \
./src/json/doc/examples/size.o \
./src/json/doc/examples/swap__array_t.o \
./src/json/doc/examples/swap__binary_t.o \
./src/json/doc/examples/swap__object_t.o \
./src/json/doc/examples/swap__reference.o \
./src/json/doc/examples/swap__string_t.o \
./src/json/doc/examples/to_bson.o \
./src/json/doc/examples/to_cbor.o \
./src/json/doc/examples/to_msgpack.o \
./src/json/doc/examples/to_ubjson.o \
./src/json/doc/examples/type.o \
./src/json/doc/examples/type_error.o \
./src/json/doc/examples/type_name.o \
./src/json/doc/examples/unflatten.o \
./src/json/doc/examples/update.o \
./src/json/doc/examples/update__range.o 

CPP_DEPS += \
./src/json/doc/examples/README.d \
./src/json/doc/examples/accept__string.d \
./src/json/doc/examples/array.d \
./src/json/doc/examples/at__object_t_key_type.d \
./src/json/doc/examples/at__object_t_key_type_const.d \
./src/json/doc/examples/at__size_type.d \
./src/json/doc/examples/at__size_type_const.d \
./src/json/doc/examples/at_json_pointer.d \
./src/json/doc/examples/at_json_pointer_const.d \
./src/json/doc/examples/back.d \
./src/json/doc/examples/basic_json__CompatibleType.d \
./src/json/doc/examples/basic_json__InputIt_InputIt.d \
./src/json/doc/examples/basic_json__basic_json.d \
./src/json/doc/examples/basic_json__copyassignment.d \
./src/json/doc/examples/basic_json__list_init_t.d \
./src/json/doc/examples/basic_json__moveconstructor.d \
./src/json/doc/examples/basic_json__nullptr_t.d \
./src/json/doc/examples/basic_json__size_type_basic_json.d \
./src/json/doc/examples/basic_json__value.d \
./src/json/doc/examples/basic_json__value_ptr.d \
./src/json/doc/examples/basic_json__value_t.d \
./src/json/doc/examples/begin.d \
./src/json/doc/examples/cbegin.d \
./src/json/doc/examples/cend.d \
./src/json/doc/examples/clear.d \
./src/json/doc/examples/contains.d \
./src/json/doc/examples/contains_json_pointer.d \
./src/json/doc/examples/count.d \
./src/json/doc/examples/crbegin.d \
./src/json/doc/examples/crend.d \
./src/json/doc/examples/diff.d \
./src/json/doc/examples/dump.d \
./src/json/doc/examples/emplace.d \
./src/json/doc/examples/emplace_back.d \
./src/json/doc/examples/empty.d \
./src/json/doc/examples/end.d \
./src/json/doc/examples/erase__IteratorType.d \
./src/json/doc/examples/erase__IteratorType_IteratorType.d \
./src/json/doc/examples/erase__key_type.d \
./src/json/doc/examples/erase__size_type.d \
./src/json/doc/examples/exception.d \
./src/json/doc/examples/find__key_type.d \
./src/json/doc/examples/flatten.d \
./src/json/doc/examples/from_bson.d \
./src/json/doc/examples/from_cbor.d \
./src/json/doc/examples/from_msgpack.d \
./src/json/doc/examples/from_ubjson.d \
./src/json/doc/examples/front.d \
./src/json/doc/examples/get__PointerType.d \
./src/json/doc/examples/get__ValueType_const.d \
./src/json/doc/examples/get_ptr.d \
./src/json/doc/examples/get_ref.d \
./src/json/doc/examples/get_to.d \
./src/json/doc/examples/insert.d \
./src/json/doc/examples/insert__count.d \
./src/json/doc/examples/insert__ilist.d \
./src/json/doc/examples/insert__range.d \
./src/json/doc/examples/insert__range_object.d \
./src/json/doc/examples/invalid_iterator.d \
./src/json/doc/examples/is_array.d \
./src/json/doc/examples/is_binary.d \
./src/json/doc/examples/is_boolean.d \
./src/json/doc/examples/is_discarded.d \
./src/json/doc/examples/is_null.d \
./src/json/doc/examples/is_number.d \
./src/json/doc/examples/is_number_float.d \
./src/json/doc/examples/is_number_integer.d \
./src/json/doc/examples/is_number_unsigned.d \
./src/json/doc/examples/is_object.d \
./src/json/doc/examples/is_primitive.d \
./src/json/doc/examples/is_string.d \
./src/json/doc/examples/is_structured.d \
./src/json/doc/examples/items.d \
./src/json/doc/examples/iterator_wrapper.d \
./src/json/doc/examples/json_pointer.d \
./src/json/doc/examples/json_pointer__back.d \
./src/json/doc/examples/json_pointer__empty.d \
./src/json/doc/examples/json_pointer__operator_add.d \
./src/json/doc/examples/json_pointer__operator_add_binary.d \
./src/json/doc/examples/json_pointer__parent_pointer.d \
./src/json/doc/examples/json_pointer__pop_back.d \
./src/json/doc/examples/json_pointer__push_back.d \
./src/json/doc/examples/json_pointer__to_string.d \
./src/json/doc/examples/max_size.d \
./src/json/doc/examples/merge_patch.d \
./src/json/doc/examples/meta.d \
./src/json/doc/examples/object.d \
./src/json/doc/examples/operator__ValueType.d \
./src/json/doc/examples/operator__equal.d \
./src/json/doc/examples/operator__equal__nullptr_t.d \
./src/json/doc/examples/operator__greater.d \
./src/json/doc/examples/operator__greaterequal.d \
./src/json/doc/examples/operator__less.d \
./src/json/doc/examples/operator__lessequal.d \
./src/json/doc/examples/operator__notequal.d \
./src/json/doc/examples/operator__notequal__nullptr_t.d \
./src/json/doc/examples/operator__value_t.d \
./src/json/doc/examples/operator_deserialize.d \
./src/json/doc/examples/operator_serialize.d \
./src/json/doc/examples/operatorarray__key_type.d \
./src/json/doc/examples/operatorarray__key_type_const.d \
./src/json/doc/examples/operatorarray__size_type.d \
./src/json/doc/examples/operatorarray__size_type_const.d \
./src/json/doc/examples/operatorjson_pointer.d \
./src/json/doc/examples/operatorjson_pointer_const.d \
./src/json/doc/examples/other_error.d \
./src/json/doc/examples/out_of_range.d \
./src/json/doc/examples/parse__array__parser_callback_t.d \
./src/json/doc/examples/parse__contiguouscontainer__parser_callback_t.d \
./src/json/doc/examples/parse__istream__parser_callback_t.d \
./src/json/doc/examples/parse__iteratortype__parser_callback_t.d \
./src/json/doc/examples/parse__string__parser_callback_t.d \
./src/json/doc/examples/parse_error.d \
./src/json/doc/examples/patch.d \
./src/json/doc/examples/push_back.d \
./src/json/doc/examples/push_back__initializer_list.d \
./src/json/doc/examples/push_back__object_t__value.d \
./src/json/doc/examples/rbegin.d \
./src/json/doc/examples/rend.d \
./src/json/doc/examples/sax_parse.d \
./src/json/doc/examples/size.d \
./src/json/doc/examples/swap__array_t.d \
./src/json/doc/examples/swap__binary_t.d \
./src/json/doc/examples/swap__object_t.d \
./src/json/doc/examples/swap__reference.d \
./src/json/doc/examples/swap__string_t.d \
./src/json/doc/examples/to_bson.d \
./src/json/doc/examples/to_cbor.d \
./src/json/doc/examples/to_msgpack.d \
./src/json/doc/examples/to_ubjson.d \
./src/json/doc/examples/type.d \
./src/json/doc/examples/type_error.d \
./src/json/doc/examples/type_name.d \
./src/json/doc/examples/unflatten.d \
./src/json/doc/examples/update.d \
./src/json/doc/examples/update__range.d 


# Each subdirectory must supply rules for building sources it contributes
src/json/doc/examples/%.o: ../src/json/doc/examples/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++17 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


